# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2025-02-04T20:24:43+00:00

from __future__ import annotations

from fastapi import FastAPI

from .routers import runs, store, threads

app = FastAPI(
    title='Agent Protocol',
    version='0.1.1',
)

app.include_router(runs.router)
app.include_router(store.router)
app.include_router(threads.router)


@app.get("/")
async def root():
    return {"message": "Gateway of the App"}
