# coding: utf-8

"""
    Agent Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ap_client.models.thread_state import ThreadState

class TestThreadState(unittest.TestCase):
    """ThreadState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThreadState:
        """Test ThreadState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThreadState`
        """
        model = ThreadState()
        if include_optional:
            return ThreadState(
                checkpoint = { },
                values = ap_client.models.values.Values(),
                messages = [
                    {
                        'key' : null
                        }
                    ],
                metadata = ap_client.models.metadata.Metadata()
            )
        else:
            return ThreadState(
                checkpoint = { },
                values = ap_client.models.values.Values(),
        )
        """

    def testThreadState(self):
        """Test ThreadState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
