# coding: utf-8

"""
    Agent Protocol

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ap_client.models.run_search_request import RunSearchRequest

class TestRunSearchRequest(unittest.TestCase):
    """RunSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunSearchRequest:
        """Test RunSearchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunSearchRequest`
        """
        model = RunSearchRequest()
        if include_optional:
            return RunSearchRequest(
                metadata = ap_client.models.metadata.Metadata(),
                status = 'pending',
                thread_id = '',
                agent_id = '',
                limit = 1,
                offset = 0
            )
        else:
            return RunSearchRequest(
        )
        """

    def testRunSearchRequest(self):
        """Test RunSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
