# generated by fastapi-codegen:
#   filename:  openapi.json

from __future__ import annotations

from fastapi import APIRouter

from ..models import (
    Any,
    ErrorResponse,
    Optional,
    Thread,
    ThreadCreate,
    ThreadPatch,
    ThreadSearchRequest,
    ThreadState,
    ThreadStateUpdate,
    ThreadStateUpdateResponse,
    ThreadsSearchPostResponse,
    ThreadsThreadIdHistoryGetResponse,
    UUID,
    Union,
)

router = APIRouter(tags=["Threads"])


@router.post(
    "/threads",
    response_model=Thread,
    responses={"409": {"model": ErrorResponse}, "422": {"model": ErrorResponse}},
    tags=["Threads"],
)
def create_thread_threads_post(body: ThreadCreate) -> Union[Thread, ErrorResponse]:
    """
    Create Thread
    """
    pass


@router.post(
    "/threads/search",
    response_model=ThreadsSearchPostResponse,
    responses={"422": {"model": ErrorResponse}},
    tags=["Threads"],
)
def search_threads_threads_search_post(
    body: ThreadSearchRequest,
) -> Union[ThreadsSearchPostResponse, ErrorResponse]:
    """
    Search Threads
    """
    pass


@router.get(
    "/threads/{thread_id}",
    response_model=Thread,
    responses={"404": {"model": ErrorResponse}, "422": {"model": ErrorResponse}},
    tags=["Threads"],
)
def get_thread_threads__thread_id__get(thread_id: UUID) -> Union[Thread, ErrorResponse]:
    """
    Get Thread
    """
    pass


@router.delete(
    "/threads/{thread_id}",
    response_model=Any,
    responses={"404": {"model": ErrorResponse}, "422": {"model": ErrorResponse}},
    tags=["Threads"],
)
def delete_thread_threads__thread_id__delete(
    thread_id: UUID,
) -> Union[Any, ErrorResponse]:
    """
    Delete Thread
    """
    pass


@router.patch(
    "/threads/{thread_id}",
    response_model=Thread,
    responses={"404": {"model": ErrorResponse}, "422": {"model": ErrorResponse}},
    tags=["Threads"],
)
def patch_thread_threads__thread_id__patch(
    thread_id: UUID, body: ThreadPatch = ...
) -> Union[Thread, ErrorResponse]:
    """
    Patch Thread
    """
    pass


@router.post(
    "/threads/{thread_id}/copy",
    response_model=Thread,
    responses={"409": {"model": ErrorResponse}, "422": {"model": ErrorResponse}},
    tags=["Threads"],
)
def copy_thread_post_threads__thread_id__copy_post(
    thread_id: UUID,
) -> Union[Thread, ErrorResponse]:
    """
    Copy Thread
    """
    pass


@router.get(
    "/threads/{thread_id}/history",
    response_model=ThreadsThreadIdHistoryGetResponse,
    responses={"422": {"model": ErrorResponse}},
    tags=["Threads"],
)
def get_thread_history_threads__thread_id__history_get(
    thread_id: UUID, limit: Optional[int] = 10, before: Optional[str] = None
) -> Union[ThreadsThreadIdHistoryGetResponse, ErrorResponse]:
    """
    Get Thread History
    """
    pass


@router.get(
    "/threads/{thread_id}/state",
    response_model=ThreadState,
    responses={"422": {"model": ErrorResponse}},
    tags=["Threads"],
)
def get_latest_thread_state_threads__thread_id__state_get(
    thread_id: UUID,
) -> Union[ThreadState, ErrorResponse]:
    """
    Get Thread State
    """
    pass


@router.post(
    "/threads/{thread_id}/state",
    response_model=ThreadStateUpdateResponse,
    responses={"422": {"model": ErrorResponse}},
    tags=["Threads"],
)
def update_thread_state_threads__thread_id__state_post(
    thread_id: UUID, body: ThreadStateUpdate = ...
) -> Union[ThreadStateUpdateResponse, ErrorResponse]:
    """
    Update Thread State
    """
    pass
