# coding: utf-8

"""
Agent Protocol

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.6
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ThreadStatus(str, Enum):
    """
    The status of the thread. One of 'idle', 'busy', 'interrupted', 'error'.
    """

    """
    allowed enum values
    """
    IDLE = "idle"
    BUSY = "busy"
    INTERRUPTED = "interrupted"
    ERROR = "error"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ThreadStatus from a JSON string"""
        return cls(json.loads(json_str))
